

# Stage 1
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build

WORKDIR /build
COPY . .
RUN dotnet publish -c Release -o /app
COPY PythonScript/Script.py /app

# Stage 2
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS final
WORKDIR /app
COPY --from=build /app .
EXPOSE 80


ENTRYPOINT ["dotnet", "PackageTracker.dll"]